// Generated by https://quicktype.io

export interface ProductsResponse {
  count: number;
  page: number;
  page_count: number;
  page_size: number;
  products: Producto[];
  skip: number;
}

export interface Producto {
  code: string;
  product_name?: string;
}
